-- 2
SELECT A.ISOCOUNTRY,
    A.CITY,
    COUNT(*) AS TOTAL
FROM AIRPORTS A
GROUP BY ROLLUP(A.ISOCOUNTRY,A.CITY)
HAVING COUNT(A.CITY) > 12
    OR (GROUPING(A.CITY) = 1 AND COUNT(*) <= 12)
ORDER BY A.ISOCOUNTRY;

-- 2.1 e 2.2
SELECT A.ISOCOUNTRY,
    A.CITY,
    COUNT(*) AS TOTAL
FROM AIRPORTS A
WHERE A.ISOCOUNTRY = 'BR'
GROUP BY ROLLUP(A.ISOCOUNTRY,A.CITY)
HAVING COUNT(A.CITY) > 12
    OR (GROUPING(A.CITY) = 1 AND COUNT(*) <= 12)
ORDER BY COUNT(*) DESC;