-- 2
SELECT 
	R.NAME AS CORRIDA,
	CONCAT(D.FORENAME,' ',D.SURNAME) AS PILOTO, 
	AVG(L.MILLISECONDS) / 1000 as SEGUNDOS
FROM RACES R
	JOIN LAPTIMES L ON R.RACEID = L.RACEID
	JOIN DRIVER D ON D.DRIVERID = L.DRIVERID
WHERE R.YEAR = 2022
GROUP BY GROUPING SETS(R.NAME, (R.NAME, CONCAT(D.FORENAME,' ',D.SURNAME)))
ORDER BY 
	R.NAME,
	CASE WHEN GROUPING(CONCAT(D.FORENAME,' ',D.SURNAME)) = 1 THEN 0 END,
	AVG(L.MILLISECONDS);


-- 2.1
SELECT 
	R.NAME AS CORRIDA,
	CONCAT(D.FORENAME,' ',D.SURNAME) AS PILOTO, 
	AVG(L.MILLISECONDS) / 1000 as SEGUNDOS
FROM RACES R
	JOIN LAPTIMES L ON R.RACEID = L.RACEID
	JOIN DRIVER D ON D.DRIVERID = L.DRIVERID
WHERE R.YEAR = 2022 AND R.NAME = 'Brazilian Grand Prix'
GROUP BY GROUPING SETS(R.NAME, (R.NAME, CONCAT(D.FORENAME,' ',D.SURNAME)))
ORDER BY 
	R.NAME,
	CASE WHEN GROUPING(CONCAT(D.FORENAME,' ',D.SURNAME)) = 1 THEN 0 END,
	AVG(L.MILLISECONDS);

-- 2.2
SELECT 
	R.NAME AS CORRIDA,
	CONCAT(D.FORENAME,' ',D.SURNAME) AS PILOTO, 
	AVG(L.MILLISECONDS) / 1000 as SEGUNDOS
FROM RACES R
	JOIN LAPTIMES L ON R.RACEID = L.RACEID
	JOIN DRIVER D ON D.DRIVERID = L.DRIVERID
WHERE 
	R.YEAR = 2022 AND 
	CONCAT(D.FORENAME,' ',D.SURNAME) = 'Yuki Tsunoda' AND
	R.NAME = 'Japanese Grand Prix'
GROUP BY GROUPING SETS(R.NAME, (R.NAME, CONCAT(D.FORENAME,' ',D.SURNAME)))
ORDER BY 
	R.NAME,
	CASE WHEN GROUPING(CONCAT(D.FORENAME,' ',D.SURNAME)) = 1 THEN 0 END,
	AVG(L.MILLISECONDS);