SELECT D.DRIVERREF,
	R.YEAR,
	SUM(DS.POINTS) AS PONTOS
FROM DRIVERSTANDINGS DS
JOIN RACES R ON DS.RACEID = R.RACEID
JOIN DRIVER D ON DS.DRIVERID = D.DRIVERID
GROUP BY DS.DRIVERID,
	R.YEAR,
	D.DRIVERREF
ORDER BY PONTOS DESC;

-- Join com tabela DRIVER e Group By de D.DRIVERREF somente para poder usar ele no select, e ver o nome do piloto ao invés do id