SELECT DRIVERREF,
	COUNT(DRIVERREF) AS NUMBER_OF_POLE_POSITIONS
FROM QUALIFYING
JOIN DRIVER ON DRIVER.DRIVERID = QUALIFYING.DRIVERID
WHERE POSITION = 1
GROUP BY DRIVERREF
ORDER BY NUMBER_OF_POLE_POSITIONS DESC
LIMIT 1;