SELECT R.NAME AS NOME_CORRIDA,
	R.YEAR AS ANO_CORRIDA,
	L.LAP AS NUMERO_VOLTA,
	
	-- tempo minimo e maximo
	FIRST_VALUE(L.MILLISECONDS) 
		OVER (PARTITION BY R.RACEID, L.LAP ORDER BY L.MILLISECONDS) AS TEMPO_MINIMO,
	LAST_VALUE(L.MILLISECONDS) 
		OVER (PARTITION BY R.RACEID, L.LAP ORDER BY L.MILLISECONDS ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS TEMPO_MAXIMO,
		
	-- piloto tempo minimo
	CONCAT(
		FIRST_VALUE(D.FORENAME) 
			OVER (PARTITION BY R.RACEID, L.LAP ORDER BY L.MILLISECONDS), ' ',
		FIRST_VALUE(D.SURNAME) 
			OVER (PARTITION BY R.RACEID, L.LAP ORDER BY L.MILLISECONDS)
	) AS PILOTO_TEMPO_MINIMO,
	
	-- piloto tempo maximo
	CONCAT(
		LAST_VALUE(D.forename) 
			OVER (PARTITION BY R.RACEID, L.LAP ORDER BY L.MILLISECONDS ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING), ' ',
		LAST_VALUE(D.SURNAME) 
			OVER (PARTITION BY R.RACEID, L.LAP ORDER BY L.MILLISECONDS ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING)
	) AS PILOTO_TEMPO_MAXIMO,
	
		
	L.MILLISECONDS AS TEMPO_VOLTA_ATUAL
FROM RACES R
JOIN LAPTIMES L ON R.RACEID = L.RACEID
JOIN DRIVER D ON D.driverid = L.driverid;