-- 1
SELECT C.NAME,
	C.NATIONALITY,
	COUNT(*) AS NUMERO_VITORIAS
FROM RESULTS R
JOIN CONSTRUCTORS C ON C.CONSTRUCTORID = R.CONSTRUCTORID
WHERE R.POSITION = 1
GROUP BY C.NAME, C.NATIONALITY;

-- 2
SELECT C.NAME,
	C.NATIONALITY,
	COUNT(*) AS NUMERO_VITORIAS,
	SUM(COUNT(*)) OVER(PARTITION BY C.NATIONALITY) AS VITORIAS_NACIONALIDADE
FROM RESULTS R
JOIN CONSTRUCTORS C ON C.CONSTRUCTORID = R.CONSTRUCTORID
WHERE R.POSITION = 1
GROUP BY C.NAME, C.NATIONALITY
ORDER BY VITORIAS_NACIONALIDADE DESC, NUMERO_VITORIAS DESC;

-- 3
SELECT C.NAME,
	C.NATIONALITY,
	COUNT(*) AS NUMERO_VITORIAS,
	SUM(COUNT(*)) OVER(PARTITION BY C.NATIONALITY) AS VITORIAS_NACIONALIDADE,
	RANK() OVER(PARTITION BY C.NATIONALITY ORDER BY COUNT(*) DESC, C.NAME) AS RANKING
FROM RESULTS R
JOIN CONSTRUCTORS C ON C.CONSTRUCTORID = R.CONSTRUCTORID
WHERE R.POSITION = 1
GROUP BY C.NAME, C.NATIONALITY
ORDER BY VITORIAS_NACIONALIDADE DESC, RANKING;