SELECT R.NAME AS NOME_CORRIDA,
	R.YEAR AS ANO_CORRIDA,
	CONCAT(D.FORENAME, ' ', D.SURNAME) AS NOME_PILOTO,
	AVG(P.MILLISECONDS) AS TEMPO_MEDIO_PITSTOP,
	RANK() OVER(PARTITION BY R.NAME, R.YEAR ORDER BY AVG(P.MILLISECONDS)) AS RANK
FROM RACES R
JOIN PITSTOPS P ON P.RACEID = R.RACEID
JOIN DRIVER D ON D.DRIVERID = P.DRIVERID
GROUP BY R.NAME, R.YEAR, NOME_PILOTO
ORDER BY R.NAME, R.YEAR;