-- Usar window function, mas precisa do distinct
SELECT DISTINCT C.NATIONALITY,
	ARRAY_AGG(C.NAME) OVER (PARTITION BY C.NATIONALITY)
FROM CONSTRUCTORS C;

-- Sem distinct, mas não usa window function
SELECT C.NATIONALITY,
	ARRAY_AGG(C.NAME)
FROM CONSTRUCTORS C
GROUP BY C.NATIONALITY;