SELECT RA.RACEID AS ID_CORRIDA,
	RA.NAME AS NOME_CORRIDA,
	RA.YEAR AS ANO_CORRIDA,
	CONCAT(D.FORENAME, ' ', D.SURNAME) AS NOME_PILOTO,
	RE.MILLISECONDS AS TEMPO,
	
	-- diferença para o primeiro colocado
	RE.MILLISECONDS - 
		FIRST_VALUE(RE.MILLISECONDS) OVER(PARTITION BY RA.RACEID ORDER BY RE.MILLISECONDS) AS DIFERANCA_PARA_PRIMEIRO,
	
	-- diferença para o que terminou imediatamente antes 
	RE.MILLISECONDS - 
		LAG(RE.MILLISECONDS, 1) OVER(PARTITION BY RA.RACEID ) AS DIFERANCA_PARA_ANETRIOR
FROM RACES RA
JOIN RESULTS RE ON RA.RACEID = RE.RACEID
JOIN DRIVER D ON RE.DRIVERID = D.DRIVERID;